/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceEstimate = IDL.Record({
  'estimatedPrice' : IDL.Nat,
  'sampleCount' : IDL.Nat,
  'priceSamples' : IDL.Vec(IDL.Nat),
});
export const ProductRecognitionResponse = IDL.Record({
  'probableProducts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});

export const idlService = IDL.Service({
  'getPriceEstimate' : IDL.Func([IDL.Nat], [PriceEstimate], []),
  'recognizeProducts' : IDL.Func([], [ProductRecognitionResponse], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceEstimate = IDL.Record({
    'estimatedPrice' : IDL.Nat,
    'sampleCount' : IDL.Nat,
    'priceSamples' : IDL.Vec(IDL.Nat),
  });
  const ProductRecognitionResponse = IDL.Record({
    'probableProducts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  
  return IDL.Service({
    'getPriceEstimate' : IDL.Func([IDL.Nat], [PriceEstimate], []),
    'recognizeProducts' : IDL.Func([], [ProductRecognitionResponse], []),
  });
};

export const init = ({ IDL }) => { return []; };